export default [
  { ignores: ['node_modules/**', 'dist/**', 'coverage/**', 'temp/**'] },
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        process: 'readonly',
        console: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        global: 'writable',
        __dirname: 'readonly',
        __filename: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        fetch: 'readonly',
        structuredClone: 'readonly',
      }
    },
    rules: {
      // ── Unused vars ───────────────────────────────────────────────
      'no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '.*'
      }],

      // ── Real bug catchers ─────────────────────────────────────────
      'no-constant-condition': 'error',
      'no-duplicate-case': 'error',
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-unreachable': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-undef': 'error',
      'eqeqeq': ['error', 'always', { null: 'ignore' }],
      'no-var': 'error',
      'prefer-const': 'error',
      'no-throw-literal': 'error',
      'no-return-assign': 'error',
      'no-eval': 'error',
      'no-new-func': 'error',
      'no-implied-eval': 'error',
      'no-extend-native': 'error',
      'no-sequences': 'error',
      'radix': 'error',
      'no-mixed-spaces-and-tabs': 'error',

      // ── Code quality ──────────────────────────────────────────────
      'no-console': 'off',
      'no-debugger': 'error',
      'no-alert': 'error',
      'no-with': 'error',
      'no-caller': 'error',
      'no-extra-bind': 'error',
      'no-useless-call': 'error',
      'no-useless-concat': 'error',
      'no-useless-escape': 'error',
      'no-useless-return': 'error',
      'no-lone-blocks': 'error',
      'no-multi-spaces': 'error',
      'no-new-wrappers': 'error',
      'no-octal-escape': 'error',
      'no-proto': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-template-curly-in-string': 'error',
      'no-unexpected-multiline': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'array-callback-return': 'error',
      'consistent-return': 'off',
      'default-case': 'off',
      'dot-notation': 'error',
      'guard-for-in': 'warn',
      'no-await-in-loop': 'off',
      'no-promise-executor-return': 'off',
      'no-constructor-return': 'error',
      'require-atomic-updates': 'off',

      // ── ES6+ ──────────────────────────────────────────────────────
      'arrow-body-style': 'off',
      'no-duplicate-imports': 'error',
      'object-shorthand': ['warn', 'always'],
      'prefer-arrow-callback': 'warn',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'warn',
      'symbol-description': 'error',
    }
  }
];
